#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
server.port: 9090

camunda.bpm.client:
  base-url: http://localhost:8080/engine-rest
#camunda.bpm.admin-user:
#  id: admin
#  password: admin